from rest_framework_simplejwt.authentication import JWTAuthentication

user = JWTAuthentication.get_user("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcwOTEyMDY1LCJpYXQiOjE2NzAzMDcyNjUsImp0aSI6ImQ3ZTljY2UyMmUxMTQxZTdhYjhlNjU0NWRiYmRhMmJhIiwidXNlcl9pZCI6ImFkbWluQHRlc3QuY29tIn0.EMONSDq9yCPkgJ_M3WLEa94nM-1N0yVr0xshPhPWUYw")
