# Generated by Django 4.1.3 on 2022-12-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonamukja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='nonamukja/%Y/%m/%d'),
        ),
    ]
