# Generated by Django 4.1.3 on 2022-12-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonamukja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='talk_link',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
