# Generated by Django 4.1.3 on 2022-11-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonamukja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='nonamukja/%Y/%m/%d'),
        ),
    ]
