# Generated by Django 4.1.3 on 2022-11-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonamukja', '0002_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='nonamukja/%Y/%m/%d'),
        ),
    ]
