# Generated by Django 4.1.3 on 2022-12-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonamukja', '0002_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='nonamukja/%Y/%m/%d'),
        ),
    ]
